#### 1. Write Python Programs to use various operators in Python

### Arithmetic operators

In [5]:
print(3+4,10-5,6*7,10/5,8%2,3**2,87//5)

7 5 42 2.0 0 9 17


### Comparison Operators

In [7]:
print(10==5, 2!=9,3>1,9<1,40>=32,55<=43)

False True True False True False


### Logical Operators

In [10]:
x=10
print(x<20 and x>5)

True


In [13]:
print(x>20 or x>5)

True


In [14]:
print(not(x < 5 and x < 10))

True


#### 2.Create list of elements and slice and dice it

In [2]:
my_list=[2,9,0,5,10,54]
my_list

[2, 9, 0, 5, 10, 54]

In [3]:
my_list[3:5]

[5, 10]

#### 3. Using while loop accept numbers until sum of numbers is less than 100

In [6]:
sum=0
a=1
while sum < 100:
    sum=sum+a
    a=a+1
    if(sum<100):
        print(sum)
    

1
3
6
10
15
21
28
36
45
55
66
78
91


#### 4. Write a python program Read & write Excel files 

To write the contents to excel file-

In [ ]:
df.to_excel('./states.xlsx')

In [ ]:
To read the contents of excel file-

In [ ]:
marksheeet= pd.read_excel('./grades.xlsx')

#### 5. Write a python program to scrape reviews from a commercial web site

##### Let the file name be “web-s”.

In [ ]:
from selenium import webdriver
from BeautifulSoup import BeautifulSoup
import pandas as pd

# to open the URL
products=[] #List to store name of the product
prices=[] #List to store price of the product
ratings=[] #List to store rating of the product
driver.get("https://www.flipkart.com/laptops/~buyback-guarantee-on-laptops-/pr?sid=6bo%2Cb5g&amp;amp;amp;uniq")

# extracting the data from the website
content = driver.page_source
soup = BeautifulSoup(content)
for a in soup.findAll('a',href=True, attrs={'class':'_31qSD5'}):
name=a.find('div', attrs={'class':'_3wU53n'})
price=a.find('div', attrs={'class':'_1vC4OE _2rQ-NK'})
rating=a.find('div', attrs={'class':'hGSR34 _2beYZw'})
products.append(name.text)
prices.append(price.text)
ratings.append(rating.text)

# Run the code to extract the data
Python web-s.py

#  Store the data in the desired format
df = pd.DataFrame({'Product Name':products,'Price':prices,'Rating':ratings})
df.to_csv('products.csv', index=False, encoding='utf-8')


#### 6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [32]:
import  numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [35]:
list=[3.4,6.7,5,91,4.6]

x=np.array(list)
print(x)

[ 3.4  6.7  5.  91.   4.6]


#### 8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [40]:
x=np.zeros(10)
x[5]=11
print(x)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
